### ISSUE TITLE
pudb flashing on every step

### ISSUE THREAD

**Issue by horida** [isaacbernat/docker-pudb#3] opened 2019-10-29 15:36 UTC
Thanks for the nice write-up. Once thing I noticed is that on every step, e.g. `n`, the pudb screen flashes (reloads completely). That is something I do not experience when debugging code running "locally" on the host.
Any idea why? Do you have the same issue?

**Comment by isaacbernat** [comment] 2019-11-09 22:12
Does this happen to you with `pudb-example` from this repo or trying docker and pudb on some other code? I just ran the instructions from the readme without any incidents.

**Comment by horida** [comment] 2019-11-11 08:41
With a python3.6 docker container

**Comment by isaacbernat** [comment] 2019-12-29 21:13
I am sorry, I couldn't reproduce the bug. I'll close the issue for the time being.

**Closed as completed by isaacbernat** 2019-12-29 21:13 UTC
